apiVersion: v1
kind: Pod
metadata:
 name: no-priv-rootful
 annotations:
    container.apparmor.security.beta.kubernetes.io/no-priv-rootful: unconfined
spec:
 containers:
   - name: no-priv-rootful
     image: quay.io/podman/stable
     args:
       - sleep
       - "1000000"
     securityContext:
       seLinuxOptions:
         type: spc_t
       capabilities:
         add:
           - "SYS_ADMIN"
           - "MKNOD"
           - "SYS_CHROOT"
           - "SETFCAP"
           - "SYS_RESOURCE"
     resources:
       limits:
         github.com/fuse: 1
